config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :pictures do
    collection do
      post :newconfirm
    end
    member do
      put :editconfirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :comment_or_image, presence: true
  belongs_to :user
  mount_uploader :image, ImageUploader

  private

  def comment_or_image
    comment.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @picture = Picture.new
  end

  def newconfirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to user_path(current_user.id), notice: "投稿を作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def editconfirm
    @picture = Picture.find(params[:id])
    @picture.comment = params[:picture][:comment]
    @picture.image = params[:picture][:image]
    render :edit if @picture.invalid?
  end

  def update
    @picture = Picture.find(params[:id])
    if params[:back]
      render :edit
    else
      if @picture.update(picture_params)
        redirect_to user_path(current_user.id), notice: "投稿の編集が完了しました！"
      else
        render :edit
      end
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to user_path(current_user.id), notice:"投稿を削除しました！"
  end

  private

  def picture_params
    params.require(:picture).permit(:comment, :image, :user_id, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      redirect_to new_user_path
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to new_user_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    if logged_in?
      @user = User.find(current_user.id)
      @pictures = current_user.pictures
    else
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def excerpt_comment(comment)
    if comment.length > 100
      comment = "#{comment.slice(0, 100)}・・・"
    end
    comment
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <%= yield %>
  </body>
</html>

app/views/pictures/edit.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="header-left hidden-xs hidden-sm col-md-4">
      </div>
      <div class="header-middle col-xs-12 col-md-4">
        <div class="header-middle-box">
          <p>
            <%= current_user.name %>
            <span class="space"><%= link_to("ログアウト", session_path(current_user.id), method: :delete) %></span>
          </p>
        </div>
      </div>
      <div class="header-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-left hidden-xs hidden-sm col-md-4">
      </div>
      <%= form_with(model: @picture, local: true, url: editconfirm_picture_path(@picture.id), method: :put) do |f| %>
        <div class="content-middle col-xs-12 col-md-4">
          <div class="content-middle-head">
            <div class="content-middle-head-errmsg">
              <% if @picture.errors.any? %>
                <div id="error_explanation" class="alert alert-danger" role="alert">
                  <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
                  <ul>
                  <% @picture.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="content-middle-head-back">
              <a class="btn btn-default" href="<%= picture_path(@picture.id) %>" role="button">戻る</a>
            </div>
          </div>
          <div class="content-middle-comment">
            <div class="content-middle-comment-title">
              <p>コメント</p>
            </div>
            <%= f.text_area :comment, size: "60x3"  %>
          </div>
          <div class="content-middle-image">
            <div class="content-middle-image-title">
              <p>画像</p>
            </div>
            <div id="img_field" onClick="$('#file').click()" >
              <%= image_tag @picture.image.url if @picture.image && @picture.image.url %>
            </div>
            <div>
              <%= f.file_field :image, class: "image", id: "file" %>
              <%= f.hidden_field :image_cache %>
            </div>
            <script type="text/javascript">
              $(function(){
                $fileField = $('#file')
                // 選択された画像を取得し表示
                $($fileField).on('change', $fileField, function(e) {
                  file = e.target.files[0]
                  reader = new FileReader(),
                  $preview = $("#img_field");

                  reader.onload = (function(file) {
                    return function(e) {
                      $preview.empty();
                      $preview.append($('<img>').attr({
                        src: e.target.result,
                        width: "100%",
                        class: "preview",
                        title: file.name
                      }));
                    };
                  })(file);
                  reader.readAsDataURL(file);
                });
              });
            </script>
          </div>
          <div class="content-middle-submit">
            <%= f.submit "編集確認" %>
          </div>
        </div>
      <% end %>
      <div class="content-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</div>

app/views/pictures/editconfirm.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="header-left hidden-xs hidden-sm col-md-4">
      </div>
      <div class="header-middle col-xs-12 col-md-4">
        <div class="header-middle-box">
          <p>
            <%= current_user.name %>
            <span class="space"><%= link_to("ログアウト", session_path(current_user.id), method: :delete) %></span>
          </p>
        </div>
      </div>
      <div class="header-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-left hidden-xs hidden-sm col-md-4">
      </div>
      <%= form_with(model: @picture, local: true ) do |f| %>
        <div class="content-middle col-xs-12 col-md-4">
          <div class="content-middle-head">
            <div class="content-middle-head-back">
              <input class="btn btn-default" type="submit" value="戻る" name="back">
            </div>
          </div>
          <div class="content-middle-comment">
            <div class="content-middle-comment-title">
              <p>コメント</p>
            </div>
            <div class="content-middle-comment-box">
              <p><%= @picture.comment %></p>
              <%= f.hidden_field :comment %>
            </div>
          </div>
          <div class="content-middle-image">
            <div class="content-middle-image-title">
              <p>画像</p>
            </div>
            <div class="content-middle-image-box">
              <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
              <%= f.hidden_field :image_cache %>
            </div>
            <div class="content-middle-submit">
              <%= f.submit "編集完了" %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="content-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="header-left hidden-xs hidden-sm col-md-4">
      </div>
      <div class="header-middle col-xs-12 col-md-4">
        <div class="header-middle-box">
          <p>
            <%= current_user.name %>
            <span class="space"><%= link_to("ログアウト", session_path(current_user.id), method: :delete) %></span>
          </p>
        </div>
      </div>
      <div class="header-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-left hidden-xs hidden-sm col-md-4">
      </div>
      <%= form_with(model: @picture, local: true, url: newconfirm_pictures_path ) do |f| %>
        <div class="content-middle col-xs-12 col-md-4">
          <div class="content-middle-head">
            <div class="content-middle-head-errmsg">
              <% if @picture.errors.any? %>
                <div id="error_explanation" class="alert alert-danger" role="alert">
                  <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
                  <ul>
                  <% @picture.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            </div>
            <div class="content-middle-head-back">
              <a class="btn btn-default" href="<%= user_path(current_user.id) %>" role="button">戻る</a>
            </div>
          </div>
          <div class="content-middle-comment">
            <div class="content-middle-comment-title">
              <p>コメント</p>
            </div>
            <%= f.text_area :comment, size: "60x3"  %>
          </div>
          <div class="content-middle-image">
            <div class="content-middle-image-title">
              <p>画像</p>
            </div>
            <div id="img_field" onClick="$('#file').click()" >
              <%= image_tag @picture.image.url if @picture.image && @picture.image.url %>
            </div>
            <div>
              <%= f.file_field :image, class: "image", id: "file" %>
              <%= f.hidden_field :image_cache %>
            </div>
            <script type="text/javascript">
              $(function(){
                $fileField = $('#file')
                $($fileField).on('change', $fileField, function(e) {
                  file = e.target.files[0]
                  reader = new FileReader(),
                  $preview = $("#img_field");
                  reader.onload = (function(file) {
                    return function(e) {
                      $preview.empty();
                      $preview.append($('<img>').attr({
                        src: e.target.result,
                        width: "100%",
                        class: "preview",
                        title: file.name
                      }));
                    };
                  })(file);
                  reader.readAsDataURL(file);
                });
              });
            </script>
          </div>
          <div class="content-middle-submit">
            <%= f.submit "投稿確認" %>
          </div>
        </div>
      <% end %>
      <div class="content-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</div>

app/views/pictures/newconfirm.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="header-left hidden-xs hidden-sm col-md-4">
      </div>
      <div class="header-middle col-xs-12 col-md-4">
        <div class="header-middle-box">
          <p>
            <%= current_user.name %>
            <span class="space"><%= link_to("ログアウト", session_path(current_user.id), method: :delete) %></span>
          </p>
        </div>
      </div>
      <div class="header-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-left hidden-xs hidden-sm col-md-4">
      </div>
      <%= form_with(model: @picture, local: true ) do |f| %>
        <div class="content-middle col-xs-12 col-md-4">
          <div class="content-middle-head">
            <div class="content-middle-head-back">
              <input class="btn btn-default" type="submit" value="戻る" name="back">
            </div>
          </div>
          <div class="content-middle-comment">
            <div class="content-middle-comment-title">
              <p>コメント</p>
            </div>
            <div class="content-middle-comment-box">
              <p><%= @picture.comment %></p>
              <%= f.hidden_field :comment %>
            </div>
          </div>
          <div class="content-middle-image">
            <div class="content-middle-image-title">
              <p>画像</p>
            </div>
            <div class="content-middle-image-box">
              <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
              <%= f.hidden_field :image_cache %>
            </div>
            <div class="content-middle-submit">
              <%= f.submit "投稿する" %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="content-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="header-left hidden-xs hidden-sm col-md-4">
      </div>
      <div class="header-middle col-xs-12 col-md-4">
        <div class="header-middle-box">
          <p>
            <%= current_user.name %>
            <span class="space"><%= link_to("ログアウト", session_path(current_user.id), method: :delete) %></span>
          </p>
        </div>
      </div>
      <div class="header-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-left hidden-xs hidden-sm col-md-4">
      </div>
      <%= form_with(model: @picture, local: true ) do |f| %>
        <%= f.hidden_field :comment %>
        <%= f.hidden_field :image %>
        <div class="content-middle col-xs-12 col-md-4">
          <div class="content-middle-head">
          </div>
          <div class="content-middle-comment">
            <div class="content-middle-comment-title">
              <p>コメント</p>
            </div>
            <div class="content-middle-comment-box">
              <p><%= @picture.comment %></p>
            </div>
          </div>
          <div class="content-middle-image">
            <div class="content-middle-image-title">
              <p>画像</p>
            </div>
            <div class="content-middle-image-box">
              <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
              <%= f.hidden_field :image_cache %>
            </div>
          </div>
          <div class="content-middle-select">
            <div class="content-middle-select-edit">
              <a class="btn btn-default" href="<%= edit_picture_path(@picture.id) %>" role="button">編集</a>
            </div>
            <div class="content-middle-select-delete">
              <a class="btn btn-default" href="<%= picture_path(@picture.id) %>" data-confirm="削除しますか？" data-method="delete" role="button">削除</a>
            </div>
            <div class="content-middle-select-back">
              <a class="btn btn-default" href="<%= user_path(current_user.id) %>" role="button">戻る</a>
            </div>
          </div>
        </div>
      <% end %>
      <div class="content-right hidden-xs hidden-sm col-md-4">
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<header class="container-fluid">
  <div class="row">
    <div class="header-left col-xs-12 col-md-6">
      <p>fakecook</p>
    </div>
      <div class="header-right col-xs-12 col-md-6">
        <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %>
          <div class="header-right-table">
            <table>
              <tr>
                <td class="header-right-title"><p>メールアドレス</p></td>
                <td class="header-right-title"><p>パスワード</p></td>
              </tr>
              <tr>
                <td>
                  <%= f.email_field :email %>
                </td>
                <td>
                  <%= f.password_field :password %>
                </td>
                <td>
                  <label class="loginbutton">
                    <%= f.submit "ログイン" %>
                  </label>
                </td>
              </tr>
            </table>
            <% flash.each do |key, value| %>
              <div class="loginerror alert alert-danger" role="alert">
                <%= content_tag(:div, value, class: "#{key}") %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
  </div>
</header>
<div class="middle">
  <div class="container-fluid">
    <div class="row">
      <div class="middle-left hidden-xs hidden-sm col-md-6">
        <div class="middle-left-box">
          <div class="introduction">
            Fakecookを使うと、料理人っぽい人たちとつながりを深められます。ケータイ、スマートフォンからもアクセスできます。
          </div>
          <div class="disp-img1"></div>
          <div class="disp-img2"></div>
          <div class="disp-img3"></div>
          <div class="disp-img4"></div>
        </div>
      </div>
      <div class="middle-right col-xs-12 col-md-6">
        <div class="middle-right-box">
          <div class="registration-text">
            <div class="registration-title">
              アカウント登録
            </div>
            <div class="registration-description">
              簡単に登録できます。
            </div>
          </div>
          <%= form_with(model: @user, local: true) do |f| %>
            <% if @user.errors.any? %>
              <div id="error_explanation" class="alert alert-danger" role="alert">
                <h4><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h4>
                <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="registration-box">
              <div class="registration-input form-group-lg">
                 <%= f.text_field :name, class: "form-control", placeholder: "名前" %>
              </div>
              <div class="registration-input form-group-lg">
                <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス" %>
              </div>
              <div class="registration-input form-group-lg">
                <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
              </div>
              <div class="registration-input form-group-lg">
                <%= f.password_field :password_confirmation, class: "form-control", placeholder: "確認用パスワード" %>
              </div>
              <div class="registration-submit">
                <input class="btn btn-success btn-lg" type="submit" value="アカウント登録">
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<footer class="footer">
</footer>

app/views/users/show.html.erb
<header>
  <div class="container-fluid">
  <div class="row">
    <div class="header-middle col-xs-12 col-md-12">
    <!-- <div class="header-middle"> -->
      <div class="header-middle-box">
        <p>
          <%= @user.name %>
          <span class="space"><%= link_to("ログアウト", session_path(current_user.id), method: :delete) %></span>
        </p>
      </div>
    </div>
  </div>
  </div>
</header>
<div class="middle-show">
  <div class="container-fluid">
    <div class="row">
      <div class="upper-middle">
        <div class="upper-middle-fill-left1 hidden-xs hidden-sm col-md-1">
        </div>
        <div class="upper-middle-fill-left2 hidden-xs hidden-sm col-md-2">
        </div>
        <div class="upper-middle-contents col-xs-12 col-md-5">
          <p><%= @user.name %></p>
        </div>
        <div class="upper-middle-fill-right hidden-xs hidden-sm col-md-4">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="under-middle">
        <div class="under-middle-fill-left1 hidden-xs hidden-sm col-md-1">
        </div>
        <div class="under-middle-fill-left2 hidden-xs hidden-sm col-md-2">
        </div>
        <div class="under-middle-contents col-xs-12 col-md-5">
          <div class="under-middle-message">
            <% if notice %>
              <div class="message-text alert alert-success" role="alert"><%= notice %></div>
            <% end %>
          </div>
          <div class="under-middle-button-area">
            <div class="button-new-post">
              <a class="btn btn-default" href="<%= new_picture_path %>" role="button">投稿を作成</a>
            </div>
          </div>
          <div class="under-middle-post-title">
            <p>投稿</p>
          </div>
          <div class="under-middle-post-area">
            <% @pictures.each do |picture| %>
            <article class="content">
              <div class="contents-box">
                <div class="contents-box-contributor">
                  <div class="contents-box-contributor-name">
                    <p><%= @user.name %>
                      <span><%= picture.updated_at.strftime('%Y年%m月%d日 %H:%M:%S') %></span>
                    </p>
                  </div>
                </div>
                <div class="contents-box-comment">
                  <p><%= excerpt_comment(picture.comment) %>
                  </p>
                </div>
                <div class="contents-box-image">
                  <%= image_tag(picture.image.url) if picture.image && picture.image.url %>
                </div>
                <div class="contents-detail">
                  <a class="btn btn-default" href="<%= picture_path(picture.id) %>" role="button">詳細</a>
                </div>
              </div>
            </article>
            <% end %>
          </div>
        </div>
        <div class="under-middle-fill-right hidden-xs hidden-sm col-md-4">
        </div>
      </div>
    </div>
  </div>
</div>